export const stateMapping: Record<string, string> = {
    "Alabama": "AL",
    "Kentucky": "KY",
    "Ohio": "OH",
    "Alaska": "AK",
    "Louisiana": "LA",
    "Oklahoma": "OK",
    "Arizona": "AZ",
    "Maine": "ME",
    "Oregon": "OR",
    "Arkansas": "AR",
    "Maryland": "MD",
    "Pennsylvania": "PA",
    "American Samoa": "AS",
    "Massachusetts": "MA",
    "Puerto Rico": "PR",
    "California": "CA",
    "Michigan": "MI",
    "Rhode Island": "RI",
    "Colorado": "CO",
    "Minnesota": "MN",
    "South Carolina": "SC",
    "Connecticut": "CT",
    "Mississippi": "MS",
    "South Dakota": "SD",
    "Delaware": "DE",
    "Missouri": "MO",
    "Tennessee": "TN",
    "District of Columbia": "DC",
    "Montana": "MT",
    "Texas": "TX",
    "Florida": "FL",
    "Nebraska": "NE",
    "Trust Territories": "TT",
    "Georgia": "GA",
    "Nevada": "NV",
    "Utah": "UT",
    "Guam": "GU",
    "New Hampshire": "NH",
    "Vermont": "VT",
    "Hawaii": "HI",
    "New Jersey": "NJ",
    "Virginia": "VA",
    "Idaho": "ID",
    "New Mexico": "NM",
    "Virgin Islands": "VI",
    "Illinois": "IL",
    "New York": "NY",
    "Washington": "WA",
    "Indiana": "IN",
    "North Carolina": "NC",
    "West Virginia": "WV",
    "Iowa": "IA",
    "North Dakota": "ND",
    "Wisconsin": "WI",
    "Kansas": "KS",
    "Northern Mariana Islands": "MP",
    "Wyoming": "WY"
  };
  
  export const streetSuffixMapping: Record<string, string> = {
    "Alley": "aly",
    "Alleyway": "alyw",
    "Anex": "anx",
    "Annex": "anx",
    "Arcade": "arc",
    "Avenue": "ave",
    "Bayou": "byu",
    "Beach": "bch",
    "Bend": "bnd",
    "Bluff": "blf",
    "Bottom": "btm",
    "Boulevard": "blvd",
    "Branch": "br",
    "Bridge": "brg",
    "Brook": "brk",
    "Bypass": "byp",
    "Camp": "cp",
    "Canyon": "cyn",
    "Cape": "cpe",
    "Causeway": "cswy",
    "Center": "ctr",
    "Circle": "cir",
    "Cliff": "clf",
    "Club": "clb",
    "Common": "cmn",
    "Corner": "cor",
    "Course": "crse",
    "Court": "ct",
    "Courts": "cts",
    "Cove": "cv",
    "Creek": "crk",
    "Crescent": "cres",
    "Crest": "crst",
    "Crossing": "xing",
    "Crossroad": "xrd",
    "Curve": "curv",
    "Dale": "dl",
    "Dam": "dm",
    "Drive": "dr",
    "Estate": "est",
    "Expressway": "expy",
    "Extension": "ext",
    "Falls": "fls",
    "Ferry": "fry",
    "Field": "fld",
    "Flat": "flt",
    "Ford": "frd",
    "Forest": "frst",
    "Forge": "frg",
    "Fork": "frk",
    "Fort": "ft",
    "Freeway": "fwy",
    "Garden": "gdn",
    "Gateway": "gtwy",
    "Glen": "gln",
    "Green": "grn",
    "Grove": "grv",
    "Harbor": "hbr",
    "Haven": "hvn",
    "Heights": "hts",
    "Highway": "hwy",
    "Hill": "hl",
    "Hollow": "holw",
    "Inlet": "inlt",
    "Island": "is",
    "Junction": "jct",
    "Key": "ky",
    "Knoll": "knl",
    "Lake": "lk",
    "Landing": "lndg",
    "Lane": "ln",
    "Light": "lgt",
    "Loaf": "lf",
    "Lock": "lck",
    "Locks": "lcks",
    "Lodge": "ldg",
    "Loop": "loop",
    "Mall": "mall",
    "Manor": "mnr",
    "Meadow": "mdw",
    "Mews": "mews",
    "Mill": "ml",
    "Mission": "msn",
    "Motorway": "mtwy",
    "Mount": "mt",
    "Mountain": "mtn",
    "Neck": "nck",
    "Orchard": "orch",
    "Overpass": "opas",
    "Park": "park",
    "Parkway": "pkwy",
    "Pass": "pass",
    "Path": "path",
    "Pike": "pike",
    "Pine": "pne",
    "Place": "pl",
    "Plain": "pln",
    "Plaza": "plz",
    "Point": "pt",
    "Port": "prt",
    "Prairie": "pr",
    "Radial": "radl",
    "Ramp": "ramp",
    "Ranch": "rnch",
    "Rapid": "rpd",
    "Rest": "rst",
    "Ridge": "rdg",
    "River": "riv",
    "Road": "rd",
    "Route": "rte",
    "Row": "row",
    "Rue": "rue",
    "Run": "run",
    "Shore": "shr",
    "Skyway": "skwy",
    "Spring": "spg",
    "Springs": "spgs",
    "Spur": "spur",
    "Square": "sq",
    "Station": "sta",
    "Stravenue": "stra",
    "Stream": "strm",
    "Street": "st",
    "Summit": "smt",
    "Terrace": "ter",
    "Throughway": "trwy",
    "Trace": "trce",
    "Track": "trak",
    "Trafficway": "trfy",
    "Trail": "trl",
    "Trailer": "trlr",
    "Tunnel": "tunl",
    "Turnpike": "tpke",
    "Underpass": "upas",
    "Union": "un",
    "Valley": "vly",
    "Viaduct": "via",
    "View": "vw",
    "Village": "vlg",
    "Ville": "vl",
    "Vista": "vis",
    "Walk": "walk",
    "Way": "way",
    "Well": "wl",
    "Wells": "wls",
    "Wye": "wye"
  };
  